language: python
python:
  - "2.7"
env:
   - TOX_ENV=py27-django17
   - TOX_ENV=py27-django18
   - TOX_ENV=py27-django19
install:
  - pip install tox
  - pip install -r development.txt
script:
  - tox -e $TOX_ENV
